# Generated by Django 3.0.9 on 2020-08-17 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200817_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date_created',
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
