# Generated by Django 3.0.10 on 2020-10-23 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200817_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
